### ISSUE TITLE
What is this for?

### ISSUE THREAD

**Issue by jpfairbanks** [vchuravy/Cthulhu.jl#6]
Hey Val,
  What is this for?
Best,
  James

Is it meant to be an actual debugging tool? Or something pedagogical? I got here from https://github.com/jrevels/Cassette.jl/issues/85.

**Comment by jrevels** [comment]
So, the initial workflow for debugging type inference issues often starts kind of like this:

1. "Huh, `f(...)` is not inferring like I thought, let's do code_typed on it"
2. "Okay, everything was inferred perfectly up to statement 10, where `g(...)` is invoked with concrete argument types, but the output type wasn't inferred well. Thus, my inference problem is somewhere in `g(...)`"
3. So now go back to 1, but recursing into `g(...)` instead of `f(...)`. Keep recursing until you hit the exact point where inference gave up/messed up/otherwise did something unexpected.

This process can be super annoying and error prone when performed manually,. For me, then, this package is hugely useful because it automates the painful parts of that workflow.

**Comment by jpfairbanks** [comment]
Thanks, so despite the funny name, it is a seriously useful tool!
